CREATE TABLE DATORY_PROC_PRE_PROCESS_FLAG (
                                              "PROC_ID" VARCHAR2(50 BYTE) NOT NULL ENABLE,
                                              "CTRY_CD" VARCHAR2(45 BYTE) NOT NULL ENABLE,
                                              "FLG" VARCHAR2(500 BYTE) NOT NULL ENABLE,
                                              PRIMARY KEY ("PROC_ID", "CTRY_CD") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
                                                  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
                                                  ) TABLESPACE "SEDF_TB" ENABLE
) SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
                                                                                                     ) TABLESPACE "SEDF_TB";
